<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Vamshi-SurfacePro" failures="1" tests="39" name="Tests.ArrayDetailsPage" time="151.492" errors="1" timestamp="2025-01-05T19:17:33 CST" skipped="2">
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_can_try_here_link_page_from_arrays_in_python" time="2.906"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_able_to_navigate_to_practice_question_page_for_search_the_array_question" time="2.861"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Valid_code_on_try_editor_for_arrays_in_python_runs_successfully" time="3.158"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Validate_user_can_navigate_to_applications_of_array" time="2.732"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Error_message_displayed_for_invalid_code_on_try_Editor_for_Array_using_list" time="3.761"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Validate_user_can_Try_here_link_page_from_Array_using_list" time="4.633"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Error_message_displayed_for_invalid_code_on_try_Editor_for_Queue_operations" time="3.407"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Validate_user_can_Try_here_link_page_from_Basic_operations_in_lists" time="3.068"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_run_the_code_in_tryEditor_for_Max_Consecutive_Ones" time="6.709"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_presented_with_error_message_for_the_code_with_the_invalid_syntax_in_tryEditor_for_search_the_array_link" time="3.470"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_can_click_on_practicequestions" time="2.877"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_able_to_navigate_to_practice_question_page_for_max_consecutive_ones_question" time="4.118"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_able_to_navigate_to_practice_question_page_for_even_number_question" time="3.706"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Valid_code_on_try_editor_for_Array_using_list_runs_successfully" time="4.173"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_presented_with_error_message_for_the_code_with_the_invalid_syntax_in_tryEditor_for_Squares_of_a_Sorted_Array" time="4.031"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_navigated_to_array_details_page_when_clicked_on_get_started" time="2.047"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="No_error_message_displayed_for_empty_code_on_try_editor_for_array_in_python" time="3.082"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_presented_with_error_message_for_the_code_with_the_invalid_syntax_in_tryEditor_for_Max_Consecutive_Ones" time="3.422"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Valid_code_on_try_editor_for_basic_operations_in_lists_runs_successfully" time="2.909"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="No_error_message_displayed_for_empty_code_on_try_editor_for_Array_using_list" time="3.111"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Error_message_displayed_for_invalid_code_on_try_Editor_for_applications_of_array" time="4.011"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_run_the_code_in_tryEditor_for_Even_number_of_digits" time="9.807"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Validate_user_can_navigate_to_basic_opertaions_in_lists" time="2.779"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Error_message_displayed_for_invalid_code_on_try_Editor_for_Basic_operations_in_lists" time="2.943"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Valid_code_on_try_editor_for_applications_of_array_runs_successfully" time="3.837"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_run_the_code_in_tryEditor_for_Squares_of_a_Sorted_Array" time="5.451"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits" time="5.155">
    <skipped/>
  </testcase> <!-- validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits -->
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_able_to_navigate_to_practice_question_page_for_sorted_array_question" time="3.348"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_submit_the_code_in_tryEditor_for_Max_Consecutive_Ones" time="6.253"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_run_the_code_in_tryEditor_for_Search_the_array_link" time="2.056">
    <error message="
Method public void Tests.ArrayDetailsPage.validate_user_is_able_to_run_the_code_in_tryEditor_for_Search_the_array_link(java.lang.String,int) throws com.fasterxml.jackson.databind.exc.InvalidFormatException,java.lang.InterruptedException,java.io.IOException,org.apache.poi.openxml4j.exceptions.OpenXML4JException requires a @DataProvider named : pythoCodeRow0 in class Utilities.TestDataProvider" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void Tests.ArrayDetailsPage.validate_user_is_able_to_run_the_code_in_tryEditor_for_Search_the_array_link(java.lang.String,int) throws com.fasterxml.jackson.databind.exc.InvalidFormatException,java.lang.InterruptedException,java.io.IOException,org.apache.poi.openxml4j.exceptions.OpenXML4JException requires a @DataProvider named : pythoCodeRow0 in class Utilities.TestDataProvider
at org.testng.internal.Parameters.findDataProvider(Parameters.java:516)
at org.testng.internal.Parameters.handleParameters(Parameters.java:739)
at org.testng.internal.Parameters.handleParameters(Parameters.java:704)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:70)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:49)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:882)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- validate_user_is_able_to_run_the_code_in_tryEditor_for_Search_the_array_link -->
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_can_navigate_to_Arrays_in_python" time="2.625"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits" time="5.207">
    <failure message="expected [2] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [2] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at PageObjects.ArrayPage.the_user_should_be_presented_with_the_run_result(ArrayPage.java:107)
at Tests.ArrayDetailsPage.validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits(ArrayDetailsPage.java:349)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:261)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits -->
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_submit_the_code_in_tryEditor_for_squares_of_a_Sorted_Array" time="6.015"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Validate_user_can_navigate_to_Arrays_using_list" time="2.700"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="No_error_message_displayed_for_empty_code_on_try_editor_for_basic_operations_in_lists" time="3.308"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_submit_the_code_in_tryEditor_for_Search_the_array_link" time="5.569"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_presented_with_error_message_for_the_code_with_the_invalid_syntax_in_tryEditor_for_Even_number_of_digits" time="3.733"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="No_error_message_displayed_for_empty_code_on_try_editor_for_applications_of_array" time="3.161"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits" time="3.353">
    <skipped/>
  </testcase> <!-- validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits -->
  <system-out/>
</testsuite> <!-- Tests.ArrayDetailsPage -->
