<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Vamshi-SurfacePro" failures="1" tests="39" name="Tests.ArrayDetailsPage" time="190.734" errors="1" timestamp="2025-01-11T11:21:31 CST" skipped="1">
  <testcase classname="Tests.ArrayDetailsPage" name="Valid_code_on_try_editor_runs_successfully" time="3.972"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_submit_the_code_in_tryEditor_for_squares_of_a_Sorted_Array" time="11.857"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits" time="9.521">
    <failure message="expected [2] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [2] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Tests.ArrayDetailsPage.validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits(ArrayDetailsPage.java:283)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:261)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits -->
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_navigated_to_array_details_page_when_clicked_on_get_started" time="2.270"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Valid_code_on_try_editor_runs_successfully" time="3.548"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_run_the_code_in_tryEditor_for_Max_Consecutive_Ones" time="9.659"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_submit_the_code_in_tryEditor_for_Max_Consecutive_Ones" time="10.238"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_able_to_navigate_to_practice_question_page_for_search_the_array_question" time="4.036"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_presented_with_error_message_for_the_code_with_the_invalid_syntax_in_tryEditor_for_Squares_of_a_Sorted_Array" time="3.749"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="No_error_message_displayed_for_empty_code_on_try_editor" time="3.042"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_can_click_on_practicequestions" time="3.069"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Error_message_displayed_for_invalid_code_on_try_Editor" time="3.592"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Validate_user_can_navigate_to_basic_opertaions_in_lists" time="3.344"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="No_error_message_displayed_for_empty_code_on_try_editor" time="3.182"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_run_the_code_in_tryEditor_for_Even_number_of_digits" time="12.365"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Error_message_displayed_for_invalid_code_on_try_Editor" time="5.047"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="No_error_message_displayed_for_empty_code_on_try_editor" time="3.066"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_presented_with_error_message_for_the_code_with_the_invalid_syntax_in_tryEditor_for_Max_Consecutive_Ones" time="3.514"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="No_error_message_displayed_for_empty_code_on_try_editor" time="3.639"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_presented_with_error_message_for_the_code_with_the_invalid_syntax_in_tryEditor_for_search_the_array_link" time="3.951"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_can_navigate_to_Arrays_in_python" time="3.121"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_can_try_here_link_page_from_arrays_in_python" time="3.183"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Validate_user_can_Try_here_link_page_from_applications_of_array" time="3.647"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Error_message_displayed_for_invalid_code_on_try_Editor" time="3.254"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Validate_user_can_Try_here_link_page_from_Array_using_list" time="3.398"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Error_message_displayed_for_invalid_code_on_try_Editor" time="4.082"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_presented_with_error_message_for_the_code_with_the_invalid_syntax_in_tryEditor_for_Even_number_of_digits" time="3.861"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_able_to_navigate_to_practice_question_page_for_max_consecutive_ones_question" time="4.850"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Valid_code_on_try_editor_runs_successfully" time="3.310"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_able_to_navigate_to_practice_question_page_for_sorted_array_question" time="3.710"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_able_to_navigate_to_practice_question_page_for_even_number_question" time="3.872"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_submit_the_code_in_tryEditor_for_Search_the_array_link" time="8.615"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Validate_user_can_Try_here_link_page_from_Basic_operations_in_lists" time="3.322"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits" time="9.517">
    <skipped/>
  </testcase> <!-- validate_user_is_able_to_submit_the_code_in_tryEditor_for_Even_number_of_digits -->
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Valid_code_on_try_editor_runs_successfully" time="5.949"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Validate_user_can_navigate_to_Arrays_using_list" time="2.588"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="Validate_user_can_navigate_to_applications_of_array" time="2.735"/>
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_run_the_code_in_tryEditor_for_Search_the_array_link" time="2.348">
    <error message="
Method public void Tests.ArrayDetailsPage.validate_user_is_able_to_run_the_code_in_tryEditor_for_Search_the_array_link(java.lang.String,int) throws com.fasterxml.jackson.databind.exc.InvalidFormatException,java.lang.InterruptedException,java.io.IOException,org.apache.poi.openxml4j.exceptions.OpenXML4JException requires a @DataProvider named : pythoCodeRow0 in class Utilities.TestDataProvider" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void Tests.ArrayDetailsPage.validate_user_is_able_to_run_the_code_in_tryEditor_for_Search_the_array_link(java.lang.String,int) throws com.fasterxml.jackson.databind.exc.InvalidFormatException,java.lang.InterruptedException,java.io.IOException,org.apache.poi.openxml4j.exceptions.OpenXML4JException requires a @DataProvider named : pythoCodeRow0 in class Utilities.TestDataProvider
at org.testng.internal.Parameters.findDataProvider(Parameters.java:516)
at org.testng.internal.Parameters.handleParameters(Parameters.java:739)
at org.testng.internal.Parameters.handleParameters(Parameters.java:704)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:70)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:49)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:882)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- validate_user_is_able_to_run_the_code_in_tryEditor_for_Search_the_array_link -->
  <system-out/>
  <testcase classname="Tests.ArrayDetailsPage" name="validate_user_is_able_to_run_the_code_in_tryEditor_for_Squares_of_a_Sorted_Array" time="8.711"/>
  <system-out/>
</testsuite> <!-- Tests.ArrayDetailsPage -->
