<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Vamshi-SurfacePro" failures="1" tests="9" name="Tests.RegistrationTestCases" time="16.873" errors="1" timestamp="2025-01-11T12:34:59 CST" skipped="1">
  <testcase classname="Tests.RegistrationTestCases" name="the_user_clicks_register_button_after_entering_a_username_with_spacebar_characters_other_than_digits_and_on_registration_form" time="1.459">
    <failure message="expected [NumpyNinja] but found [Registration]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [NumpyNinja] but found [Registration]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Tests.RegistrationTestCases.the_user_clicks_register_button_after_entering_a_username_with_spacebar_characters_other_than_digits_and_on_registration_form(RegistrationTestCases.java:103)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:261)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- the_user_clicks_register_button_after_entering_a_username_with_spacebar_characters_other_than_digits_and_on_registration_form -->
  <system-out/>
  <testcase classname="Tests.RegistrationTestCases" name="the_user_clicks_register_button_after_entering_a_password_with_characters_less_than_eight_on_registration_form" time="1.561"/>
  <system-out/>
  <testcase classname="Tests.RegistrationTestCases" name="the_user_clicks_register_button_with_all_fields_empty_on_registration_form" time="0.628">
    <error message="
Method public void Tests.RegistrationTestCases.the_user_clicks_register_button_with_all_fields_empty_on_registration_form(java.lang.String,int) throws java.io.IOException,org.apache.poi.openxml4j.exceptions.OpenXML4JException,java.lang.InterruptedException requires a @DataProvider named : RegisterRow0 in class Utilities.TestDataProvider" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void Tests.RegistrationTestCases.the_user_clicks_register_button_with_all_fields_empty_on_registration_form(java.lang.String,int) throws java.io.IOException,org.apache.poi.openxml4j.exceptions.OpenXML4JException,java.lang.InterruptedException requires a @DataProvider named : RegisterRow0 in class Utilities.TestDataProvider
at org.testng.internal.Parameters.findDataProvider(Parameters.java:516)
at org.testng.internal.Parameters.handleParameters(Parameters.java:739)
at org.testng.internal.Parameters.handleParameters(Parameters.java:704)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:70)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:49)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:882)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- the_user_clicks_register_button_with_all_fields_empty_on_registration_form -->
  <system-out/>
  <testcase classname="Tests.RegistrationTestCases" name="TC_01_validate_RegistrationIsSuccessful_onAllValidCredentials" time="7.175"/>
  <system-out/>
  <testcase classname="Tests.RegistrationTestCases" name="TC_02_validate_Error_Message_when_DifferentPasswordsIn_Both_PswdFields" time="1.561"/>
  <system-out/>
  <testcase classname="Tests.RegistrationTestCases" name="the_user_clicks_register_button_after_entering_a_password_with_only_numeric_data_on_registration_form" time="1.559"/>
  <system-out/>
  <testcase classname="Tests.RegistrationTestCases" name="user_clicks_on_login_button_from_registration_page" time="1.074"/>
  <system-out/>
  <testcase classname="Tests.RegistrationTestCases" name="user_clicks_on_sign_in_button_from_registration_page" time="1.143"/>
  <system-out/>
  <testcase classname="Tests.RegistrationTestCases" name="the_user_clicks_register_button_after_entering_a_username_with_spacebar_characters_other_than_digits_and_on_registration_form" time="0.713">
    <skipped/>
  </testcase> <!-- the_user_clicks_register_button_after_entering_a_username_with_spacebar_characters_other_than_digits_and_on_registration_form -->
  <system-out/>
</testsuite> <!-- Tests.RegistrationTestCases -->
